version: '3.5'

services:
  localstack:
    image: localstack/localstack
    container_name: ${PREFIX-sciencebeam-editor}-localstack
    restart: unless-stopped
    environment:
      - SERVICES=s3,sqs
    volumes:
      - './.localstack/startup:/docker-entrypoint-initaws.d:ro'
      - './.localstack/config:/etc/localstackconf:ro'
      - './articles:/tmp/articles:ro'
    ports:
      - 4566:4566
    healthcheck:
      test: 'echo -e "GET /health\n\n" | nc ${PREFIX-sciencebeam-editor}-localstack 4566'
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 60s

  mongo:
    image: mongo
    container_name: ${PREFIX-sciencebeam-editor}-mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo ${PREFIX-sciencebeam-editor}-mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s

  grobid:
    image: lfoppiano/grobid:${GROBID_TAG-0.6.1}
    container_name: ${PREFIX-sciencebeam-editor}-grobid
    restart: unless-stopped
    environment:
        - JAVA_OPTS=-Xmx1g

  sciencebeam:
    image: elifesciences/sciencebeam:${SCIENCEBEAM_TAG-0.0.10}
    container_name: ${PREFIX-sciencebeam-editor}-sciencebeam
    restart: unless-stopped
    depends_on:
      - grobid
    command: ./server.sh \
        --host=0.0.0.0 --port=8075 \
        --pipeline grobid \
        --grobid-url http://${PREFIX-sciencebeam-editor}-grobid:8070/api

  editor-article-store:
    image: liberoadmin/editor-article-store:${TAG-latest}
    container_name: ${PREFIX-sciencebeam-editor}-article-store
    restart: unless-stopped
    depends_on:
      - mongo
      - localstack
    environment:
      - PORT=8080
      - DB_ENDPOINT=${PREFIX-sciencebeam-editor}-mongo:27017
      - DB_NAME=editor
      - DB_USER=root
      - DB_PASSWORD=password
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY=key
      - AWS_SECRET_ACCESS_KEY=secret
      - AWS_BUCKET_INPUT_EVENT_QUEUE_URL=http://${PREFIX-sciencebeam-editor}-localstack:4566/000000000000/EditorImportQueue
      - AWS_ENDPOINT=http://${PREFIX-sciencebeam-editor}-localstack:4566
      - AWS_SRC_BUCKET=s3-editor-source-bucket
      - AWS_EDITOR_BUCKET=s3-editor-destination-bucket

  editor-client:
    image: liberoadmin/editor-client:${TAG-latest}
    container_name: ${PREFIX-sciencebeam-editor}-client
    restart: unless-stopped
    depends_on:
      - editor-article-store

  file-watcher:
    build:
      context: './src/file-watcher'
    image: file-watcher:${TAG-local}
    container_name: ${PREFIX-sciencebeam-editor}-file-watcher
    restart: unless-stopped
    depends_on:
      - mongo
      - localstack
    environment: 
      - S3_BUCKET=s3-editor-source-bucket
      - AWS_ENDPOINT=http://${PREFIX-sciencebeam-editor}-localstack:4566
    volumes: 
      - "./articles:/bucket-to-watch:ro"

  bridge:
    build:
      context: './src/bridge'
    image: bridge:${TAG-local}
    container_name: ${PREFIX-sciencebeam-editor}-bridge
    restart: unless-stopped
    environment: 
      - DEPOSIT_PATH=/articles
    volumes: 
      - "./articles:/articles:rw"

  demo:
    image: nginx:alpine
    container_name: ${PREFIX-sciencebeam-editor}-demo
    volumes:
      - './src/demo:/usr/share/nginx/html:ro'

  nginx:
    image: nginx:alpine
    container_name: ${PREFIX-sciencebeam-editor}-nginx
    depends_on:
      - editor-article-store
      - editor-client
      - sciencebeam
      - demo
    environment:
      - PREFIX=${PREFIX-sciencebeam-editor}
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    volumes:
      - './.nginx:/etc/nginx/templates:ro'
    ports:
      - ${PORT-4000}:80